name: build for commit

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

